### ISSUE TITLE
Schema mismatch for Twenty v0.33.4

### ISSUE THREAD

**Issue by raphspeaks** [shodgson/n8n-nodes-twenty#3]
I’m seeing the following error message on the Person Node:

The field 'nameFields' is not defined by type ``FullNameUpdateInput`` I believe this indicates a mismatch between the GraphQL query or mutation and the schema defined. 

Here's a breakdown of the issue:

The GraphQL schema defines an input type called ``FullNameUpdateInput``. This input type likely expects specific fields for updating a full name, but it does not have a field called ``nameFields``.

The query /mutation is trying to pass an object with a ``nameFields`` field to the ``FullNameUpdateInput`` type. This is causing the error because the schema doesn't recognize that field.

The error received from Twenty is as follows:

```
BaseGraphQLError [GraphQLError]: Field "nameFields" is not defined by type "FullNameUpdateInput".
app-server-1    |         at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:134:11)
app-server-1    |         at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:117:34)
app-server-1    |         at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:49:14)
app-server-1    |         at coerceInputValue (/app/node_modules/graphql/utilities/coerceInputValue.js:32:10)
app-server-1    |         at coerceVariableValues (/app/node_modules/@graphql-tools/executor/cjs/execution/values.js:68:65)
app-server-1    |         at getVariableValues (/app/node_modules/@graphql-tools/executor/cjs/execution/values.js:19:25)
app-server-1    |         at buildExecutionContext (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:184:69)
app-server-1    |         at execute (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:33:24)
app-server-1    |         at /app/node_modules/@graphql-tools/executor/cjs/execution/normalizedExecutor.js:15:81
app-server-1    |         at new ValueOrPromise (/app/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21) {
app-server-1    |       message: 'Variable "$data" got invalid value { nameFields: { firstName: “Joe", lastName: “Momma" } } at "data.name"; Field "nameFields" is not defined by type "FullNameUpdateInput".',
app-server-1    |       path: undefined,
```

Similar issue for other nested/related fields:

```
BaseGraphQLError [GraphQLError]: Field "phonesFields" is not defined by type "PhonesUpdateInput".
app-server-1    |         at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:134:11)
app-server-1    |         at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:117:34)
app-server-1    |         at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:49:14)
app-server-1    |         at coerceInputValue (/app/node_modules/graphql/utilities/coerceInputValue.js:32:10)
app-server-1    |         at coerceVariableValues (/app/node_modules/@graphql-tools/executor/cjs/execution/values.js:68:65)
app-server-1    |         at getVariableValues (/app/node_modules/@graphql-tools/executor/cjs/execution/values.js:19:25)
app-server-1    |         at buildExecutionContext (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:184:69)
app-server-1    |         at execute (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:33:24)
app-server-1    |         at /app/node_modules/@graphql-tools/executor/cjs/execution/normalizedExecutor.js:15:81
app-server-1    |         at new ValueOrPromise (/app/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21) {
app-server-1    |       message: 'Variable "$data" got invalid value { phonesFields: { additionalPhones: [], primaryPhoneCountryCode: "", primaryPhoneNumber: “555-555-1212" } } at "data.phones"; Field "phonesFields" is not defined by type "PhonesUpdateInput".',
app-server-1    |       path: undefined,
app-server-1    |       locations: undefined,
app-server-1    |       extensions: {
app-server-1    |         code: 'INTERNAL_SERVER_ERROR',
app-server-1    |         response: 'Variable "$data" got invalid value { phonesFields: { additionalPhones: [], primaryPhoneCountryCode: "", primaryPhoneNumber: “555-555-1212" } } at "data.phones"; Field "phonesFields" is not defined by type "PhonesUpdateInput".
```

Without digging too deeply, I think we’re probably looking for something like:

```
{
  displayName: 'Name',
  name: 'name',
  placeholder: 'Add Name Field',
  type: 'fixedCollection', 
  default: {},
  description: 'Contact’s name',
  options: [
    {
      displayName: 'First Name',
      name: 'firstName',
      type: 'string',
      default: '',
    },
    {
      displayName: 'Last Name',
      name: 'lastName',
      type: 'string',
      default: '',
    }
  ]
}
```
Resulting in the following GraphQL:
```
input FullNameUpdateInput {
  firstName: String
  lastName: String
}
```

Updated needed somewhere these areas:

https://github.com/shodgson/n8n-nodes-twenty/blob/d4bbb86f44a67e43c912152eb59e1753abe60385/nodes/Twenty/descriptions/PersonDescription.ts#L323

https://github.com/shodgson/n8n-nodes-twenty/blob/d4bbb86f44a67e43c912152eb59e1753abe60385/nodes/Twenty/descriptions/PersonDescription.ts#L724

https://github.com/shodgson/n8n-nodes-twenty/blob/d4bbb86f44a67e43c912152eb59e1753abe60385/nodes/Twenty/descriptions/PersonDescription.ts#L1210

**Comment by raphspeaks** [comment]
@shodgson - Join the conversation here if you’re able to:

https://discord.com/channels/1130383047699738754/1322607634016108554

**Comment by shodgson** [comment]
plugin v0.0.4 is now compatible with the Twenty v0.40.7 schema
